version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "marlon"
      POSTGRES_PASSWORD: "marlon"
    ports:
      - "15432:5432"
    volumes:
      - D:\Users\Marlon\Desktop\Dev\docker\volumes\postgres
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "marlon@marlon.com"
      PGADMIN_DEFAULT_PASSWORD: "marlon"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge