version: '3.8'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: marlon
      ME_CONFIG_BASICAUTH_PASSWORD: marlon
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - C:\Users\1545 IRON V4\Desktop\Dev\docker\volumes\mongo
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
